### ISSUE TITLE
QMdiSubWindow loses its window frame

### ISSUE THREAD

**Issue by arielja87** [mstuttgart/qdarkgraystyle#3]
Hello! really enjoy using your theme! I have a QMdiArea with several subwindows. When I apply the theme the windows lose their frames, and thus the ability to be resized (On a Windows computer)

I've tried to disable the Qt.FramelessWindowHint flag, no luck. And I can't tell what in the stylesheet might be causing this. Any thoughts?

**Comment by mstuttgart** [comment]
Hi @arielja87 ! You tested you app with default Qt5 theme?
