### ISSUE TITLE
Background Colors

### ISSUE THREAD

**Issue by Harshil783** [mstuttgart/qdarkgraystyle#5]
Can you tell the background color you use in this project?

**Comment by mstuttgart** [comment]
Hi @Harshil783 ! The color is #323232

https://github.com/mstuttgart/qdarkgraystyle/blob/develop/qdarkgraystyle/style.qss#L37

**Comment by Harshil783** [comment]
Hey! @mstuttgart I Want to know if you can style more qmessagebox like their message box and hover and pressed

**Comment by Harshil783** [comment]
And Also more style menu like editing border of white color!

**Comment by mstuttgart** [comment]
Sorry @Harshil783 .

Yes, it is possible to customize the other widgets as you mentioned. I adapted only the widgets that I use in another project of mine that uses pyqt. You can style this widget in this file https://github.com/mstuttgart/qdarkgraystyle/blob/develop/qdarkgraystyle/style.qss file and compile it.
